name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run linter
        run: bun run lint
      - name: Run tests
        run: bun run test:run
      - name: Build project
        run: bun run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7
  # Separate job for type checking
  typecheck:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Type check
        run: bunx tsc --noEmit
  # Job for checking build size and performance
  build-check:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build and analyze bundle
        run: "bun run build\necho \"## Build Size Report\" >> $GITHUB_STEP_SUMMARY\necho \"| File | Size |\" >> $GITHUB_STEP_SUMMARY\necho \"|------|------|\" >> $GITHUB_STEP_SUMMARY\nfind dist -name \"*.js\" -o -name \"*.css\" | while read file; do\n  size=$(du -h \"$file\" | cut -f1)\n  echo \"| $file | $size |\" >> $GITHUB_STEP_SUMMARY\ndone "
